title: Jayshree Rathi
description: Personal blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsrathi.com" # your custom domain

# Build settings
markdown: kramdown
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default" 